#!/bin/bash

### This script is called after the user uninstalls the application.

if [ "${wizard_data_action:-}" == "delete" ]; then
  SSH_CONFIG_FILE="/etc/ssh/sshd_config"
  [ -f "${SSH_CONFIG_FILE}.bak" ] && cp -f "${SSH_CONFIG_FILE}.bak" "${SSH_CONFIG_FILE}"
fi

exit 0
