#!/bin/bash

### This script is called after the user uninstalls the application.

[ "${wizard_data_action:-}" == "delete" ] && {
  SSH_CONFIG_FILE="/etc/ssh/sshd_config"
  cp -f "${SSH_CONFIG_FILE}.bak" "${SSH_CONFIG_FILE}"
}

exit 0
